### PR TITLE
Filter posts that have no content 

### PR DESCRIPTION
**Pull request by lluiscamino**
Hello :)

I modified the filter condition so that posts with no content are not considered (https://github.com/sleepyfran/readder/issues/1)

### CODE REVIEW

**Comment by sleepyfran** [comment]
Hey! Thank you for the pull request! This looks good, however I’ve seen various times in which the content is _null_ too, can you filter those too? Once we have that scenario covered I’ll complete the pull request 😃

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sleepyfran** [comment]
Just updated the issue too! Sorry I didn’t put it there!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by sleepyfran** [comment]
Also, if you can, add another test case to the posts test cases to check that it filters correctly both empty and _null_ values 😄

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by lluiscamino** [comment]
Ok, so I edited the filter to add the check for `null` values.

I also added a test case to check it, but I had to edit the `createPost` function. I hope this is OK, if you want me to change something just let me know. 👍

**Pull request merged**
